### ISSUE TITLE
mpa view transition

### ISSUE THREAD

**Issue by Tobi-De** [Tobi-De/falco_blueprint_basic#53]
https://www.bram.us/2024/05/17/multi-page-application-view-transitions-are-here-google-i-o-2024/?ref=dailydev

```css
@view-transition {
	navigation: auto;
}
```
